#!/bin/sh
bspc monitor $(bspc query -M | head -n1) -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap           12
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a microsoft-edge desktop='^2'
bspc rule -a Microsoft-edge desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a floating state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off


pkill -x setxkbmap
sleep 0.1
setxkbmap -layout us,gr,ru,ua -option grp:alt_shift_toggle &

pkill -x sxhkd
sleep 0.1
sxhkd &

pkill -x feh
sleep 0.1
feh --bg-fill ~/Pictures/wallpapers/0.jpg &

pkill -x polybar
sleep 0.1
polybar top &

pkill -x picom
sleep 0.1
picom --config ~/.config/picom/picom.conf &